services:
  web:
    build: .
    container_name: todo_list_api
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: ${DEBUG:-True}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-your_default_secret_key}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db
    restart: unless-stopped

volumes:
  sqlite_data: