[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# Para rodar contra a aplicação local em Docker:
# pytest --base-url=http://localhost:8000
addopts = --tb=short -v
